client_fxboard\build\install\client_fxboard\bin\client_fxboard
client_fxmap\build\install\client_fxmap\bin\client_fxmap
client_swingboard\build\install\client_swingboard\bin\client_swingboard
client_admin\build\install\client_admin\bin\client_admin
